In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_excel('C:/Users/hrashikesh hegde/Downloads/stark_data1.xlsx')

In [3]:
dataset.head()

Character   Age  Gender  Survived
0    Eddard  52.0    Male         0
1      John  27.0    Male         1
2      Arya  21.0  Female         1
3      Bran  19.0    Male         1
4      Robb   NaN    Male         0

In [4]:
dataset.shape

(6, 4)

In [5]:
X_gender=dataset.iloc[:,3].values
X_gender

array([0, 1, 1, 1, 0, 1], dtype=int64)

In [6]:
X_dummy1=pd.get_dummies(X_gender)

In [7]:
X_dummy1

0  1
0  1  0
1  0  1
2  0  1
3  0  1
4  1  0
5  0  1

In [8]:
X_dummy2=pd.get_dummies(X_gender,drop_first=True)

In [9]:
X_dummy2

1
0  0
1  1
2  1
3  1
4  0
5  1

In [10]:
#Read the data
dataset=pd.read_excel('C:/Users/hrashikesh hegde/Downloads/stark_data1.xlsx')

In [11]:
dataset.head()

Character   Age  Gender  Survived
0    Eddard  52.0    Male         0
1      John  27.0    Male         1
2      Arya  21.0  Female         1
3      Bran  19.0    Male         1
4      Robb   NaN    Male         0

In [12]:
dataset.shape

(6, 4)

In [13]:
X=dataset.iloc[:,:-1].values

In [14]:
X

array([['Eddard', 52.0, 'Male'],
       ['John', 27.0, 'Male'],
       ['Arya', 21.0, 'Female'],
       ['Bran', 19.0, 'Male'],
       ['Robb', nan, 'Male'],
       ['Sansa', 24.0, 'Female']], dtype=object)

In [15]:
from sklearn.preprocessing import Imputer
imputer=Imputer(missing_values='NaN',strategy='mean',axis=0)
imputer.fit(X[:,1:2])
X[:,1:2]=imputer.transform(X[:,1:2])
X[:,1:2]


D:\anaconda\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[52.0],
       [27.0],
       [21.0],
       [19.0],
       [28.6],
       [24.0]], dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X=LabelEncoder()
X[:,2]=labelencoder_X.fit_transform(X[:,2])
X[:,2]

array([1, 1, 0, 1, 1, 0], dtype=object)

In [17]:
X[:,0]=labelencoder_X.fit_transform(X[:,0])
X[:,0]

array([2, 3, 0, 1, 4, 5], dtype=object)

In [18]:
X

array([[2, 52.0, 1],
       [3, 27.0, 1],
       [0, 21.0, 0],
       [1, 19.0, 1],
       [4, 28.6, 1],
       [5, 24.0, 0]], dtype=object)

In [19]:
onehotencoder=OneHotEncoder(categorical_features=[0])
X=onehotencoder.fit_transform(X).toarray()
X

D:\anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
D:\anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[ 0. ,  0. ,  1. ,  0. ,  0. ,  0. , 52. ,  1. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. ,  0. , 27. ,  1. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. , 21. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ,  0. , 19. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. , 28.6,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1. , 24. ,  0. ]])

In [20]:
X[:,1:]

array([[ 0. ,  1. ,  0. ,  0. ,  0. , 52. ,  1. ],
       [ 0. ,  0. ,  1. ,  0. ,  0. , 27. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. , 21. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. , 19. ,  1. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. , 28.6,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  1. , 24. ,  0. ]])

In [21]:
import numpy as np
import pandas as pd

In [22]:
dataset=pd.read_csv('C:/Users/hrashikesh hegde/Downloads/purchase_salary.csv')

In [23]:
dataset.shape

(400, 5)

In [24]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [25]:
X=dataset.iloc[:,2:4]
X.head()

Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [26]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
std_X=sc.fit_transform(X)

In [27]:
std_X[0:5]

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059]])

In [28]:
help(StandardScaler)

Help on class StandardScaler in module sklearn.preprocessing.data:

class StandardScaler(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  StandardScaler(copy=True, with_mean=True, with_std=True)
 |  
 |  Standardize features by removing the mean and scaling to unit variance
 |  
 |  The standard score of a sample `x` is calculated as:
 |  
 |      z = (x - u) / s
 |  
 |  where `u` is the mean of the training samples or zero if `with_mean=False`,
 |  and `s` is the standard deviation of the training samples or one if
 |  `with_std=False`.
 |  
 |  Centering and scaling happen independently on each feature by computing
 |  the relevant statistics on the samples in the training set. Mean and
 |  standard deviation are then stored to be used on later data using the
 |  `transform` method.
 |  
 |  Standardization of a dataset is a common requirement for many
 |  machine learning estimators: they might behave badly if the
 |  individual features do not more or less look like 

In [31]:
from sklearn.preprocessing import MinMaxScaler
MinMaxScalerX=MinMaxScaler()
MN_X=MinMaxScalerX.fit_transform(X)