In [1]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sb

In [2]:
df=pd.read_csv("C:/Users/hrashikesh hegde/Downloads/insurance_data.csv")
df.head()


age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [3]:
x=df.age.values 
y=df.bought_insurance.values

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

In [5]:
x_test

array([60, 49, 62], dtype=int64)

In [6]:
y_test

array([1, 1, 1], dtype=int64)

In [7]:
x_train

array([18, 40, 47, 55, 52, 50, 45, 55, 26, 25, 22, 56, 54, 21, 19, 27, 61,
       18, 23, 28, 25, 58, 29, 46], dtype=int64)

In [8]:
y_train

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1], dtype=int64)

In [9]:
from sklearn.model_selection import KFold
import numpy as np

In [10]:
kf=KFold(10)
for train,test in kf.split(x):
    print('trian: %s test: %s'%(x[train],x[test]))

trian: [52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23] test: [22 25 47]
trian: [22 25 47 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23] test: [52 46 56]
trian: [22 25 47 52 46 56 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23] test: [55 60 62]
trian: [22 25 47 52 46 56 55 60 62 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23] test: [61 18 28]
trian: [22 25 47 52 46 56 55 60 62 61 18 28 55 25 58 19 18 21 26 40 45 50 54 23] test: [27 29 49]
trian: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 19 18 21 26 40 45 50 54 23] test: [55 25 58]
trian: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 26 40 45 50 54 23] test: [19 18 21]
trian: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 45 50 54
 23] test: [26 40]
trian: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 54
 23] test: [45 50]
trian: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45
 50] test: [54 23]
