In [2]:
#first model 
#kmeans clustering

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
dataset=pd.read_excel('C:/Users/hrashikesh hegde/Downloads/cricket_data.xlsx')
dataset.shape

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
Player     13 non-null object
Runs       13 non-null int64
Wickets    13 non-null int64
dtypes: int64(2), object(1)
memory usage: 440.0+ bytes


In [5]:
dataset.head()

Player   Runs  Wickets
0  Sachin Tendulkar  18426      192
1      Kripal Singh  12458        0
2      Fakhar Zaman   9840      421
3   Aavishkar Salvi   3467      480
4         Abbas Ali   4877      512

In [11]:
f1=dataset['Runs'].values
f2=dataset['Wickets'].values
X=np.array(list(zip(f1,f2)))
print(X)


[[18426   192]
 [12458     0]
 [ 9840   421]
 [ 3467   480]
 [ 4877   512]
 [10405    12]
 [ 3287   575]
 [ 2145   437]
 [ 4562   502]
 [ 2543   381]
 [10151    14]
 [10889     0]
 [11579   142]]


In [14]:
from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=2)
kmeans=kmeans.fit(X)
labels=kmeans.predict(X)
centroids=kmeans.cluster_centers_

In [15]:
print(labels)

[1 1 1 0 0 1 0 0 0 0 1 1 1]


In [17]:
pd.DataFrame({"Player":dataset['Player'],
             "Runs":dataset["Runs"],
             "Wickets":dataset["Wickets"],
             })

Player   Runs  Wickets
0   Sachin Tendulkar  18426      192
1       Kripal Singh  12458        0
2       Fakhar Zaman   9840      421
3    Aavishkar Salvi   3467      480
4          Abbas Ali   4877      512
5         Brian Lara  10405       12
6     James Anderson   3287      575
7         Dale Steyn   2145      437
8        Wasim Akram   4562      502
9      Glenn McGrath   2543      381
10       Chris Gayle  10151       14
11      Rahul Dravid  10889        0
12    Jacques Kallis  11579      142

In [18]:
centroids

array([[ 3480.16666667,   481.16666667],
       [11964.        ,   111.57142857]])